In [1]:
import pandas as pd
import sqlite3
from IPython.display import display

## **Datos E-commerce**

In [3]:
clientes_data = [
    (1, "Ana Gómez", "Bogotá", "2024-01-10"),
    (2, "Luis Pérez", "Medellín", "2024-01-15"),
    (3, "Sofía Ramírez", "Cali", "2024-02-01"),
    (4, "Carlos Torres", "Bogotá", "2024-02-20"),
    (5, "Valentina Ruiz", "Barranquilla", "2024-03-05"),
    (6, "Mateo Castro", "Cartagena", "2024-03-10"),
    (7, "Laura Sánchez", "Bogotá", "2024-03-15"),
    (8, "Andrés Mejía", "Medellín", "2024-03-18"),
    (9, "Camila Herrera", "Cali", "2024-03-22"),
    (10, "Juan López", "Bucaramanga", "2024-03-25"),
]

pedidos_data = [
    (101, 1, "2024-03-01", 150),
    (102, 2, "2024-03-02", 80),
    (103, 1, "2024-03-05", 220),
    (104, 3, "2024-03-06", 60),
    (105, 4, "2024-03-08", 300),
    (106, 5, "2024-03-10", 95),
    (107, 6, "2024-03-11", 180),
    (108, 7, "2024-03-12", 250),
    (109, 8, "2024-03-13", 130),
    (110, 9, "2024-03-15", 75),
    (111, 10, "2024-03-16", 210),
    (112, 2, "2024-03-18", 160),
    (113, 3, "2024-03-19", 90),
    (114, 5, "2024-03-20", 140),
    (115, 7, "2024-03-21", 110),
]

productos_data = [
    (501, "Audífonos", "Tecnología", 80),
    (502, "Teclado", "Tecnología", 70),
    (503, "Cuaderno", "Papelería", 40),
    (504, "Mouse inalámbrico", "Tecnología", 120),
    (505, "Bolígrafo", "Papelería", 20),
    (506, "Agenda", "Papelería", 20),
    (507, "Monitor", "Tecnología", 300),
    (508, "Silla ergonómica", "Oficina", 450),
    (509, "Escritorio", "Oficina", 600),
    (510, "Calculadora", "Papelería", 50),
    (511, "Webcam", "Tecnología", 90),
    (512, "Lámpara", "Oficina", 85),
]

detalle_pedido_data = [
    (101, 501, 1, 80),
    (101, 502, 1, 70),
    (102, 503, 2, 40),
    (103, 504, 1, 120),
    (103, 501, 1, 80),
    (103, 505, 1, 20),
    (104, 505, 3, 20),
    (105, 502, 2, 70),
    (105, 504, 1, 120),
    (105, 506, 2, 20),
    (106, 510, 1, 50),
    (106, 503, 1, 40),
    (107, 511, 2, 90),
    (108, 507, 1, 300),
    (109, 502, 1, 70),
    (109, 505, 3, 20),
    (110, 506, 2, 20),
    (110, 505, 1, 20),
    (111, 504, 1, 120),
    (111, 511, 1, 90),
    (112, 501, 2, 80),
    (113, 503, 1, 40),
    (113, 510, 1, 50),
    (114, 512, 1, 85),
    (114, 505, 2, 20),
    (115, 503, 1, 40),
    (115, 506, 2, 20),
    (115, 510, 1, 50),
]

## **Crear dataframes**

In [4]:
clientes = pd.DataFrame(clientes_data, columns=["cliente_id", "nombre", "ciudad", "fecha_registro"])
pedidos = pd.DataFrame(pedidos_data, columns=["pedido_id", "cliente_id", "fecha_pedido", "total"])
productos = pd.DataFrame(productos_data, columns=["producto_id", "nombre_producto", "categoria", "precio"])
detalle_pedido = pd.DataFrame(detalle_pedido_data, columns=["pedido_id", "producto_id", "cantidad", "precio_unitario"])

clientes["fecha_registro"] = pd.to_datetime(clientes["fecha_registro"])
pedidos["fecha_pedido"] = pd.to_datetime(pedidos["fecha_pedido"])

display(clientes.head())
display(pedidos.head())
display(productos.head())
display(detalle_pedido.head())

   cliente_id          nombre        ciudad fecha_registro
0           1       Ana Gómez        Bogotá     2024-01-10
1           2      Luis Pérez      Medellín     2024-01-15
2           3   Sofía Ramírez          Cali     2024-02-01
3           4   Carlos Torres        Bogotá     2024-02-20
4           5  Valentina Ruiz  Barranquilla     2024-03-05

   pedido_id  cliente_id fecha_pedido  total
0        101           1   2024-03-01    150
1        102           2   2024-03-02     80
2        103           1   2024-03-05    220
3        104           3   2024-03-06     60
4        105           4   2024-03-08    300

   producto_id    nombre_producto   categoria  precio
0          501          Audífonos  Tecnología      80
1          502            Teclado  Tecnología      70
2          503           Cuaderno   Papelería      40
3          504  Mouse inalámbrico  Tecnología     120
4          505          Bolígrafo   Papelería      20

   pedido_id  producto_id  cantidad  precio_unitario
0        101          501         1               80
1        101          502         1               70
2        102          503         2               40
3        103          504         1              120
4        103          501         1               80

## **Crear tablas en sql**

In [5]:
conn = sqlite3.connect(":memory:")

clientes.to_sql("clientes", conn, index=False, if_exists="replace")
pedidos.to_sql("pedidos", conn, index=False, if_exists="replace")
productos.to_sql("productos", conn, index=False, if_exists="replace")
detalle_pedido.to_sql("detalle_pedido", conn, index=False, if_exists="replace")

28

### **Funciones auxiliares**

In [6]:
def run_sql(query):
    return pd.read_sql_query(query, conn)

## **1) SELECT y FROM**

In [8]:
query_1 = """
SELECT *
FROM clientes
LIMIT 5
"""
sql_1 = run_sql(query_1)
sql_1

   cliente_id          nombre        ciudad       fecha_registro
0           1       Ana Gómez        Bogotá  2024-01-10 00:00:00
1           2      Luis Pérez      Medellín  2024-01-15 00:00:00
2           3   Sofía Ramírez          Cali  2024-02-01 00:00:00
3           4   Carlos Torres        Bogotá  2024-02-20 00:00:00
4           5  Valentina Ruiz  Barranquilla  2024-03-05 00:00:00

In [9]:
clientes.head(5)

   cliente_id          nombre        ciudad fecha_registro
0           1       Ana Gómez        Bogotá     2024-01-10
1           2      Luis Pérez      Medellín     2024-01-15
2           3   Sofía Ramírez          Cali     2024-02-01
3           4   Carlos Torres        Bogotá     2024-02-20
4           5  Valentina Ruiz  Barranquilla     2024-03-05

## **2) Seleccionar columnas específicas**

In [10]:
query_2 = """
SELECT nombre, ciudad
FROM clientes
"""
sql_2 = run_sql(query_2)
sql_2

           nombre        ciudad
0       Ana Gómez        Bogotá
1      Luis Pérez      Medellín
2   Sofía Ramírez          Cali
3   Carlos Torres        Bogotá
4  Valentina Ruiz  Barranquilla
5    Mateo Castro     Cartagena
6   Laura Sánchez        Bogotá
7    Andrés Mejía      Medellín
8  Camila Herrera          Cali
9      Juan López   Bucaramanga

In [11]:
clientes[["nombre", "ciudad"]]

           nombre        ciudad
0       Ana Gómez        Bogotá
1      Luis Pérez      Medellín
2   Sofía Ramírez          Cali
3   Carlos Torres        Bogotá
4  Valentina Ruiz  Barranquilla
5    Mateo Castro     Cartagena
6   Laura Sánchez        Bogotá
7    Andrés Mejía      Medellín
8  Camila Herrera          Cali
9      Juan López   Bucaramanga

## **3) WHERE**

In [12]:
query_3 = """
SELECT *
FROM clientes
WHERE ciudad = 'Bogotá'
"""
sql_3 = run_sql(query_3)
sql_3

   cliente_id         nombre  ciudad       fecha_registro
0           1      Ana Gómez  Bogotá  2024-01-10 00:00:00
1           4  Carlos Torres  Bogotá  2024-02-20 00:00:00
2           7  Laura Sánchez  Bogotá  2024-03-15 00:00:00

In [14]:
clientes[clientes["ciudad"] == "Bogotá"].reset_index(drop=True)

   cliente_id         nombre  ciudad fecha_registro
0           1      Ana Gómez  Bogotá     2024-01-10
1           4  Carlos Torres  Bogotá     2024-02-20
2           7  Laura Sánchez  Bogotá     2024-03-15

## **4) WHERE con múltiples condiciones**

In [15]:
query_4 = """
SELECT *
FROM pedidos
WHERE total > 100 AND total < 250
"""
sql_4 = run_sql(query_4)
sql_4

   pedido_id  cliente_id         fecha_pedido  total
0        101           1  2024-03-01 00:00:00    150
1        103           1  2024-03-05 00:00:00    220
2        107           6  2024-03-11 00:00:00    180
3        109           8  2024-03-13 00:00:00    130
4        111          10  2024-03-16 00:00:00    210
5        112           2  2024-03-18 00:00:00    160
6        114           5  2024-03-20 00:00:00    140
7        115           7  2024-03-21 00:00:00    110

In [16]:
pedidos[(pedidos["total"] > 100) & (pedidos["total"] < 250)].reset_index(drop=True)

   pedido_id  cliente_id fecha_pedido  total
0        101           1   2024-03-01    150
1        103           1   2024-03-05    220
2        107           6   2024-03-11    180
3        109           8   2024-03-13    130
4        111          10   2024-03-16    210
5        112           2   2024-03-18    160
6        114           5   2024-03-20    140
7        115           7   2024-03-21    110

## **5) IN**

In [17]:
query_5 = """
SELECT nombre, ciudad
FROM clientes
WHERE ciudad IN ('Bogotá', 'Medellín')
"""
sql_5 = run_sql(query_5)
sql_5

          nombre    ciudad
0      Ana Gómez    Bogotá
1     Luis Pérez  Medellín
2  Carlos Torres    Bogotá
3  Laura Sánchez    Bogotá
4   Andrés Mejía  Medellín

In [ ]:
clientes[clientes["ciudad"].isin(["Bogotá", "Medellín"])][["nombre", "ciudad"]].reset_index(drop=True)

          nombre    ciudad
0      Ana Gómez    Bogotá
1     Luis Pérez  Medellín
2  Carlos Torres    Bogotá
3  Laura Sánchez    Bogotá
4   Andrés Mejía  Medellín

## **6) ORDER BY**

In [28]:
query_6 = """
SELECT pedido_id, total
FROM pedidos
ORDER BY total DESC
"""
sql_6 = run_sql(query_6)
sql_6

    pedido_id  total
0         105    300
1         108    250
2         103    220
3         111    210
4         107    180
5         112    160
6         101    150
7         114    140
8         109    130
9         115    110
10        106     95
11        113     90
12        102     80
13        110     75
14        104     60

In [27]:
pedidos[["pedido_id", "total"]].sort_values("total", ascending=False).reset_index(drop = True)

    pedido_id  total
0         105    300
1         108    250
2         103    220
3         111    210
4         107    180
5         112    160
6         101    150
7         114    140
8         109    130
9         115    110
10        106     95
11        113     90
12        102     80
13        110     75
14        104     60

## **7) LIMIT**

In [35]:
query_7 = """
SELECT *
FROM productos
ORDER BY precio DESC
LIMIT 5
"""
sql_7 = run_sql(query_7)
sql_7

   producto_id    nombre_producto   categoria  precio
0          509         Escritorio     Oficina     600
1          508   Silla ergonómica     Oficina     450
2          507            Monitor  Tecnología     300
3          504  Mouse inalámbrico  Tecnología     120
4          511             Webcam  Tecnología      90

In [36]:
productos.sort_values("precio", ascending=False).head(5)

    producto_id    nombre_producto   categoria  precio
8           509         Escritorio     Oficina     600
7           508   Silla ergonómica     Oficina     450
6           507            Monitor  Tecnología     300
3           504  Mouse inalámbrico  Tecnología     120
10          511             Webcam  Tecnología      90

## **8) Funciones agregadas**

In [29]:
query_8 = """
SELECT 
    COUNT(*) AS numero_pedidos,
    AVG(total) AS promedio_compra,
    MIN(total) AS minimo,
    MAX(total) AS maximo,
    SUM(total) AS suma_total
FROM pedidos
"""
sql_8 = run_sql(query_8)
sql_8

   numero_pedidos  promedio_compra  minimo  maximo  suma_total
0              15            150.0      60     300        2250

In [30]:
pd.DataFrame({
    "numero_pedidos": [pedidos.shape[0]],
    "promedio_compra": [pedidos["total"].mean()],
    "minimo": [pedidos["total"].min()],
    "maximo": [pedidos["total"].max()],
    "suma_total": [pedidos["total"].sum()],
})

   numero_pedidos  promedio_compra  minimo  maximo  suma_total
0              15            150.0      60     300        2250

## **9) GROUP BY**

In [31]:
query_9 = """
SELECT cliente_id, SUM(total) AS total_comprado
FROM pedidos
GROUP BY cliente_id
ORDER BY total_comprado DESC
"""
sql_9 = run_sql(query_9)
sql_9

   cliente_id  total_comprado
0           1             370
1           7             360
2           4             300
3           2             240
4           5             235
5          10             210
6           6             180
7           3             150
8           8             130
9           9              75

In [33]:
pedidos.groupby("cliente_id", as_index=False)["total"]\
    .sum()\
    .rename(columns={"total": "total_comprado"})\
    .sort_values("total_comprado", ascending=False)

   cliente_id  total_comprado
0           1             370
6           7             360
3           4             300
1           2             240
4           5             235
9          10             210
5           6             180
2           3             150
7           8             130
8           9              75

## **10) GROUP BY con HAVING**

In [34]:
query_10 = """
SELECT cliente_id, SUM(total) AS total_comprado
FROM pedidos
GROUP BY cliente_id
HAVING SUM(total) > 200
ORDER BY total_comprado DESC
"""
sql_10 = run_sql(query_10)
sql_10

   cliente_id  total_comprado
0           1             370
1           7             360
2           4             300
3           2             240
4           5             235
5          10             210

In [38]:
pandas_10 = (
    pedidos.groupby("cliente_id", as_index=False)["total"]
    .sum()
    .rename(columns={"total": "total_comprado"})
)
pandas_10[pandas_10["total_comprado"] > 200].sort_values("total_comprado", ascending=False)

   cliente_id  total_comprado
0           1             370
6           7             360
3           4             300
1           2             240
4           5             235
9          10             210

## **11) INNER JOIN**

In [39]:
query_11 = """
SELECT 
    c.nombre,
    c.ciudad,
    p.pedido_id,
    p.fecha_pedido,
    p.total
FROM clientes c
INNER JOIN pedidos p
    ON c.cliente_id = p.cliente_id
ORDER BY p.pedido_id
"""
sql_11 = run_sql(query_11)
sql_11.head(10)

           nombre        ciudad  pedido_id         fecha_pedido  total
0       Ana Gómez        Bogotá        101  2024-03-01 00:00:00    150
1      Luis Pérez      Medellín        102  2024-03-02 00:00:00     80
2       Ana Gómez        Bogotá        103  2024-03-05 00:00:00    220
3   Sofía Ramírez          Cali        104  2024-03-06 00:00:00     60
4   Carlos Torres        Bogotá        105  2024-03-08 00:00:00    300
5  Valentina Ruiz  Barranquilla        106  2024-03-10 00:00:00     95
6    Mateo Castro     Cartagena        107  2024-03-11 00:00:00    180
7   Laura Sánchez        Bogotá        108  2024-03-12 00:00:00    250
8    Andrés Mejía      Medellín        109  2024-03-13 00:00:00    130
9  Camila Herrera          Cali        110  2024-03-15 00:00:00     75

In [41]:
(clientes.merge(pedidos, on="cliente_id", how="inner")
[["nombre", "ciudad", "pedido_id", "fecha_pedido", "total"]]
.sort_values("pedido_id"))

            nombre        ciudad  pedido_id fecha_pedido  total
0        Ana Gómez        Bogotá        101   2024-03-01    150
2       Luis Pérez      Medellín        102   2024-03-02     80
1        Ana Gómez        Bogotá        103   2024-03-05    220
4    Sofía Ramírez          Cali        104   2024-03-06     60
6    Carlos Torres        Bogotá        105   2024-03-08    300
7   Valentina Ruiz  Barranquilla        106   2024-03-10     95
9     Mateo Castro     Cartagena        107   2024-03-11    180
10   Laura Sánchez        Bogotá        108   2024-03-12    250
12    Andrés Mejía      Medellín        109   2024-03-13    130
13  Camila Herrera          Cali        110   2024-03-15     75
14      Juan López   Bucaramanga        111   2024-03-16    210
3       Luis Pérez      Medellín        112   2024-03-18    160
5    Sofía Ramírez          Cali        113   2024-03-19     90
8   Valentina Ruiz  Barranquilla        114   2024-03-20    140
11   Laura Sánchez        Bogotá        115   2024-03-21    110

## **12) LEFT JOIN**

In [42]:
query_12 = """
SELECT 
    c.cliente_id,
    c.nombre,
    p.pedido_id
FROM clientes c
LEFT JOIN pedidos p
    ON c.cliente_id = p.cliente_id
ORDER BY c.cliente_id, p.pedido_id
"""
sql_12 = run_sql(query_12)
sql_12.head(15)

    cliente_id          nombre  pedido_id
0            1       Ana Gómez        101
1            1       Ana Gómez        103
2            2      Luis Pérez        102
3            2      Luis Pérez        112
4            3   Sofía Ramírez        104
5            3   Sofía Ramírez        113
6            4   Carlos Torres        105
7            5  Valentina Ruiz        106
8            5  Valentina Ruiz        114
9            6    Mateo Castro        107
10           7   Laura Sánchez        108
11           7   Laura Sánchez        115
12           8    Andrés Mejía        109
13           9  Camila Herrera        110
14          10      Juan López        111

In [43]:
(
    clientes.merge(pedidos[["cliente_id", "pedido_id"]], on="cliente_id", how="left")
    .sort_values(["cliente_id", "pedido_id"])
)

    cliente_id          nombre        ciudad fecha_registro  pedido_id
0            1       Ana Gómez        Bogotá     2024-01-10        101
1            1       Ana Gómez        Bogotá     2024-01-10        103
2            2      Luis Pérez      Medellín     2024-01-15        102
3            2      Luis Pérez      Medellín     2024-01-15        112
4            3   Sofía Ramírez          Cali     2024-02-01        104
5            3   Sofía Ramírez          Cali     2024-02-01        113
6            4   Carlos Torres        Bogotá     2024-02-20        105
7            5  Valentina Ruiz  Barranquilla     2024-03-05        106
8            5  Valentina Ruiz  Barranquilla     2024-03-05        114
9            6    Mateo Castro     Cartagena     2024-03-10        107
10           7   Laura Sánchez        Bogotá     2024-03-15        108
11           7   Laura Sánchez        Bogotá     2024-03-15        115
12           8    Andrés Mejía      Medellín     2024-03-18        109
13           9  Camila Herrera          Cali     2024-03-22        110
14          10      Juan López   Bucaramanga     2024-03-25        111

## **13) JOIN con múltiples tablas**

In [47]:
query_13 = """
SELECT
    c.nombre,
    p.pedido_id,
    pr.nombre_producto,
    dp.cantidad,
    dp.precio_unitario
FROM clientes c
INNER JOIN pedidos p
    ON c.cliente_id = p.cliente_id
INNER JOIN detalle_pedido dp
    ON p.pedido_id = dp.pedido_id
INNER JOIN productos pr
    ON dp.producto_id = pr.producto_id
ORDER BY c.nombre,p.pedido_id
"""
sql_13 = run_sql(query_13)
sql_13.head(15)

            nombre  pedido_id    nombre_producto  cantidad  precio_unitario
0        Ana Gómez        101          Audífonos         1               80
1        Ana Gómez        101            Teclado         1               70
2        Ana Gómez        103          Audífonos         1               80
3        Ana Gómez        103  Mouse inalámbrico         1              120
4        Ana Gómez        103          Bolígrafo         1               20
5     Andrés Mejía        109            Teclado         1               70
6     Andrés Mejía        109          Bolígrafo         3               20
7   Camila Herrera        110          Bolígrafo         1               20
8   Camila Herrera        110             Agenda         2               20
9    Carlos Torres        105            Teclado         2               70
10   Carlos Torres        105  Mouse inalámbrico         1              120
11   Carlos Torres        105             Agenda         2               20
12      Juan López        111  Mouse inalámbrico         1              120
13      Juan López        111             Webcam         1               90
14   Laura Sánchez        108            Monitor         1              300

In [48]:
(
    clientes.merge(pedidos, on="cliente_id", how="inner")
    .merge(detalle_pedido, on="pedido_id", how="inner")
    .merge(productos, on="producto_id", how="inner")
    [["nombre", "pedido_id", "nombre_producto", "cantidad", "precio_unitario"]]
    .sort_values(["nombre","pedido_id"])
)

            nombre  pedido_id    nombre_producto  cantidad  precio_unitario
0        Ana Gómez        101          Audífonos         1               80
1        Ana Gómez        101            Teclado         1               70
2        Ana Gómez        103  Mouse inalámbrico         1              120
3        Ana Gómez        103          Audífonos         1               80
4        Ana Gómez        103          Bolígrafo         1               20
22    Andrés Mejía        109            Teclado         1               70
23    Andrés Mejía        109          Bolígrafo         3               20
24  Camila Herrera        110             Agenda         2               20
25  Camila Herrera        110          Bolígrafo         1               20
10   Carlos Torres        105            Teclado         2               70
11   Carlos Torres        105  Mouse inalámbrico         1              120
12   Carlos Torres        105             Agenda         2               20
26      Juan López        111  Mouse inalámbrico         1              120
27      Juan López        111             Webcam         1               90
18   Laura Sánchez        108            Monitor         1              300
19   Laura Sánchez        115           Cuaderno         1               40
20   Laura Sánchez        115             Agenda         2               20
21   Laura Sánchez        115        Calculadora         1               50
5       Luis Pérez        102           Cuaderno         2               40
6       Luis Pérez        112          Audífonos         2               80
17    Mateo Castro        107             Webcam         2               90
7    Sofía Ramírez        104          Bolígrafo         3               20
8    Sofía Ramírez        113           Cuaderno         1               40
9    Sofía Ramírez        113        Calculadora         1               50
13  Valentina Ruiz        106        Calculadora         1               50
14  Valentina Ruiz        106           Cuaderno         1               40
15  Valentina Ruiz        114            Lámpara         1               85
16  Valentina Ruiz        114          Bolígrafo         2               20

## **14) Ventas por categoría**

In [49]:
query_14 = """
SELECT
    pr.categoria,
    SUM(dp.cantidad * dp.precio_unitario) AS ventas_totales
FROM detalle_pedido dp
INNER JOIN productos pr
    ON dp.producto_id = pr.producto_id
GROUP BY pr.categoria
ORDER BY ventas_totales DESC
"""
sql_14 = run_sql(query_14)
sql_14

    categoria  ventas_totales
0  Tecnología            1530
1   Papelería             670
2     Oficina              85

In [51]:
tmp = detalle_pedido.merge(productos, on="producto_id", how="inner")
tmp["ventas_linea"] = tmp["cantidad"] * tmp["precio_unitario"]

(
    tmp.groupby("categoria", as_index=False)["ventas_linea"]
    .sum()
    .rename(columns={"ventas_linea": "ventas_totales"})
    .sort_values("ventas_totales", ascending=False)
)

    categoria  ventas_totales
2  Tecnología            1530
1   Papelería             670
0     Oficina              85

## **15) Top clientes por monto comprado**

In [52]:
query_15 = """
SELECT
    c.nombre,
    SUM(p.total) AS total_comprado
FROM clientes c
INNER JOIN pedidos p
    ON c.cliente_id = p.cliente_id
GROUP BY c.nombre
ORDER BY total_comprado DESC
LIMIT 5
"""
sql_15 = run_sql(query_15)
sql_15

           nombre  total_comprado
0       Ana Gómez             370
1   Laura Sánchez             360
2   Carlos Torres             300
3      Luis Pérez             240
4  Valentina Ruiz             235

In [53]:
(
    clientes.merge(pedidos, on="cliente_id", how="inner")
    .groupby("nombre", as_index=False)["total"]
    .sum()
    .rename(columns={"total": "total_comprado"})
    .sort_values("total_comprado", ascending=False)
    .head(5)
)

           nombre  total_comprado
0       Ana Gómez             370
5   Laura Sánchez             360
3   Carlos Torres             300
6      Luis Pérez             240
9  Valentina Ruiz             235

## **16) CASE WHEN**

In [54]:
query_16 = """
SELECT
    pedido_id,
    total,
    CASE
        WHEN total >= 200 THEN 'Alto'
        WHEN total >= 100 THEN 'Medio'
        ELSE 'Bajo'
    END AS segmento_compra
FROM pedidos
ORDER BY pedido_id
"""
sql_16 = run_sql(query_16)
sql_16.head(10)

   pedido_id  total segmento_compra
0        101    150           Medio
1        102     80            Bajo
2        103    220            Alto
3        104     60            Bajo
4        105    300            Alto
5        106     95            Bajo
6        107    180           Medio
7        108    250            Alto
8        109    130           Medio
9        110     75            Bajo

In [57]:
import numpy as np

pandas_16 = pedidos[["pedido_id", "total"]].copy()

pandas_16["segmento_compra"] = np.where(
    pandas_16["total"] >= 200, "Alto",
    np.where(
        (pandas_16["total"] >= 100) & (pandas_16["total"] < 200), "Medio", 
        "Bajo"
    )
)

pandas_16.sort_values("pedido_id").head(10)

   pedido_id  total segmento_compra
0        101    150           Medio
1        102     80            Bajo
2        103    220            Alto
3        104     60            Bajo
4        105    300            Alto
5        106     95            Bajo
6        107    180           Medio
7        108    250            Alto
8        109    130           Medio
9        110     75            Bajo

## **17) Subquery**

In [58]:
query_17 = """
SELECT *
FROM pedidos
WHERE total > (
    SELECT AVG(total)
    FROM pedidos
)
ORDER BY total DESC
"""
sql_17 = run_sql(query_17)
sql_17

   pedido_id  cliente_id         fecha_pedido  total
0        105           4  2024-03-08 00:00:00    300
1        108           7  2024-03-12 00:00:00    250
2        103           1  2024-03-05 00:00:00    220
3        111          10  2024-03-16 00:00:00    210
4        107           6  2024-03-11 00:00:00    180
5        112           2  2024-03-18 00:00:00    160

In [59]:
promedio_total = pedidos["total"].mean()
pedidos[pedidos["total"] > promedio_total].sort_values("total", ascending=False)

    pedido_id  cliente_id fecha_pedido  total
4         105           4   2024-03-08    300
7         108           7   2024-03-12    250
2         103           1   2024-03-05    220
10        111          10   2024-03-16    210
6         107           6   2024-03-11    180
11        112           2   2024-03-18    160

## **18) Query final completa**

In [60]:
query_18 = """
SELECT
    c.nombre,
    c.ciudad,
    pr.categoria,
    SUM(dp.cantidad * dp.precio_unitario) AS gasto_total
FROM clientes c
INNER JOIN pedidos p
    ON c.cliente_id = p.cliente_id
INNER JOIN detalle_pedido dp
    ON p.pedido_id = dp.pedido_id
INNER JOIN productos pr
    ON dp.producto_id = pr.producto_id
GROUP BY c.nombre, c.ciudad, pr.categoria
ORDER BY gasto_total DESC
"""
sql_18 = run_sql(query_18)
sql_18.head(15)

            nombre        ciudad   categoria  gasto_total
0        Ana Gómez        Bogotá  Tecnología          350
1    Laura Sánchez        Bogotá  Tecnología          300
2    Carlos Torres        Bogotá  Tecnología          260
3       Juan López   Bucaramanga  Tecnología          210
4     Mateo Castro     Cartagena  Tecnología          180
5       Luis Pérez      Medellín  Tecnología          160
6    Sofía Ramírez          Cali   Papelería          150
7    Laura Sánchez        Bogotá   Papelería          130
8   Valentina Ruiz  Barranquilla   Papelería          130
9   Valentina Ruiz  Barranquilla     Oficina           85
10      Luis Pérez      Medellín   Papelería           80
11    Andrés Mejía      Medellín  Tecnología           70
12    Andrés Mejía      Medellín   Papelería           60
13  Camila Herrera          Cali   Papelería           60
14   Carlos Torres        Bogotá   Papelería           40

In [64]:
tmp = (
    clientes.merge(pedidos, on="cliente_id", how="inner")
    .merge(detalle_pedido, on="pedido_id", how="inner")
    .merge(productos, on="producto_id", how="inner")
)

tmp["gasto_total"] = tmp["cantidad"] * tmp["precio_unitario"]

(
    tmp.groupby(["nombre", "ciudad", "categoria"], as_index=False)["gasto_total"]
    .sum()
    .sort_values("gasto_total", ascending=False)
).head(15)

            nombre        ciudad   categoria  gasto_total
1        Ana Gómez        Bogotá  Tecnología          350
9    Laura Sánchez        Bogotá  Tecnología          300
6    Carlos Torres        Bogotá  Tecnología          260
7       Juan López   Bucaramanga  Tecnología          210
12    Mateo Castro     Cartagena  Tecnología          180
11      Luis Pérez      Medellín  Tecnología          160
13   Sofía Ramírez          Cali   Papelería          150
8    Laura Sánchez        Bogotá   Papelería          130
15  Valentina Ruiz  Barranquilla   Papelería          130
14  Valentina Ruiz  Barranquilla     Oficina           85
10      Luis Pérez      Medellín   Papelería           80
3     Andrés Mejía      Medellín  Tecnología           70
2     Andrés Mejía      Medellín   Papelería           60
4   Camila Herrera          Cali   Papelería           60
5    Carlos Torres        Bogotá   Papelería           40